name: Build Minecraft Mod

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-with: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17' # Строго 17, как указано в вашем build.gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew build

    - name: Capture Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AICraft-Jar
        path: build/libs/*.jar
